# Translation script to convert Chinese text to English in SQL file

$inputFile = "01-create-digital-lending-complete.sql"
$content = Get-Content $inputFile -Raw -Encoding UTF8

# Translation mappings
$translations = @{
    # Section headers
    "第二部分：创建表定义" = "Part 2: Create Table Definitions"
    "第三部分：创建表单定义" = "Part 3: Create Form Definitions"
    "第四部分：创建动作定义" = "Part 4: Create Action Definitions"
    "第五部分：输出摘要信息" = "Part 5: Output Summary Information"
    
    # Table descriptions
    "主表：贷款申请" = "Main Table: Loan Application"
    "贷款申请主表，记录贷款的核心信息" = "Main loan application table, records core loan information"
    "子表：申请人信息" = "Sub Table: Applicant Information"
    "申请人个人信息（支持主申请人和共同申请人）" = "Applicant personal information (supports primary and co-applicants)"
    "子表：财务信息" = "Sub Table: Financial Information"
    "申请人财务状况信息" = "Applicant financial status information"
    "子表：抵押物信息" = "Sub Table: Collateral Details"
    "抵押物/担保品详细信息（用于有抵押贷款）" = "Collateral/security details (for secured loans)"
    "关联表：信用检查结果" = "Relation Table: Credit Check Results"
    "信用局检查结果记录" = "Credit bureau check result records"
    "关联表：审批历史" = "Relation Table: Approval History"
    "所有审批操作的历史记录" = "Historical records of all approval operations"
    "关联表：文档附件" = "Relation Table: Documents"
    "贷款申请的支持文档和附件" = "Supporting documents and attachments for loan applications"
    
    # Field descriptions
    "主键" = "Primary key"
    "申请编号（唯一）" = "Application number (unique)"
    "申请日期" = "Application date"
    "贷款类型（个人/房贷/车贷/企业）" = "Loan type (Personal/Mortgage/Auto/Business)"
    "申请金额" = "Loan amount"
    "贷款期限（月）" = "Loan tenure (months)"
    "年利率（%）" = "Annual interest rate (%)"
    "月供金额" = "EMI amount"
    "贷款用途" = "Loan purpose"
    "申请状态" = "Application status"
    "当前流程阶段" = "Current workflow stage"
    "风险评级（低/中/高）" = "Risk rating (Low/Medium/High)"
    "信用评分" = "Credit score"
    "批准日期" = "Approval date"
    "放款日期" = "Disbursement date"
    "拒绝原因" = "Rejection reason"
    "创建人" = "Created by"
    "创建时间" = "Created at"
    "更新时间" = "Updated at"
    
    # Applicant fields
    "外键：贷款申请ID" = "Foreign key: Loan Application ID"
    "申请人类型（主申请人/共同申请人）" = "Applicant type (Primary/Co-applicant)"
    "全名" = "Full name"
    "出生日期" = "Date of birth"
    "性别" = "Gender"
    "婚姻状况" = "Marital status"
    "国籍" = "Nationality"
    "证件类型" = "ID type"
    "证件号码" = "ID number"
    "手机号码" = "Mobile number"
    "电子邮箱" = "Email"
    "当前居住地址" = "Current address"
    "永久地址" = "Permanent address"
    "在当前地址居住年限" = "Years at current address"
    
    # Financial fields
    "就业类型（受薪/自雇/企业主）" = "Employment type (Salaried/Self-employed/Business owner)"
    "雇主/公司名称" = "Employer/Company name"
    "职业/职位" = "Occupation/Position"
    "工作年限" = "Years of employment"
    "月收入" = "Monthly income"
    "其他收入" = "Other income"
    "月支出" = "Monthly expenses"
    "现有贷款总额" = "Existing loans total"
    "现有月供总额" = "Existing EMI total"
    "主要银行名称" = "Primary bank name"
    "银行账号" = "Account number"
    "账户类型（储蓄/活期）" = "Account type (Savings/Current)"
    
    # Collateral fields
    "抵押物类型（房产/车辆/证券/定期存款）" = "Collateral type (Property/Vehicle/Securities/Fixed deposit)"
    "抵押物详细描述" = "Collateral description"
    "估值" = "Estimated value"
    "估值日期" = "Valuation date"
    "估值师姓名" = "Valuer name"
    "所有权证明文件" = "Ownership proof document"
    "产权负担状态" = "Encumbrance status"
    
    # Credit check fields
    "信用局名称" = "Credit bureau name"
    "检查日期" = "Check date"
    "评分范围（如：300-900）" = "Score range (e.g., 300-900)"
    "信用历史长度（月）" = "Credit history length (months)"
    "总账户数" = "Total accounts"
    "活跃账户数" = "Active accounts"
    "逾期账户数" = "Delinquent accounts"
    "总债务" = "Total debt"
    "信用使用率（%）" = "Credit utilization (%)"
    "还款历史评级" = "Payment history rating"
    "备注" = "Remarks"
    
    # Approval history fields
    "审批阶段名称" = "Stage name"
    "审批人姓名" = "Approver name"
    "审批人角色" = "Approver role"
    "操作类型" = "Action type"
    "决定（批准/拒绝/退回）" = "Decision (Approve/Reject/Return)"
    "操作日期" = "Action date"
    "审批意见" = "Comments"
    "批准条件" = "Approval conditions"
    
    # Document fields
    "文档类型" = "Document type"
    "文档名称" = "Document name"
    "文件存储路径" = "File path"
    "文件大小（字节）" = "File size (bytes)"
    "上传日期" = "Upload date"
    "上传人" = "Uploaded by"
    "验证状态" = "Verification status"
    "验证人" = "Verified by"
    "验证日期" = "Verification date"
    
    # Form descriptions
    "贷款申请表单" = "Loan Application Form"
    "完整的贷款申请表单，供客户填写" = "Complete loan application form for customers to fill out"
    "信用检查表单" = "Credit Check Form"
    "信用审查员记录信用检查结果的弹窗表单" = "Popup form for credit officers to record credit check results"
    "风险评估表单" = "Risk Assessment Form"
    "风险评估员评估贷款风险的弹窗表单" = "Popup form for risk officers to assess loan risk"
    "审批表单" = "Loan Approval Form"
    "经理审批贷款申请的表单" = "Form for managers to approve loan applications"
    "放款表单" = "Loan Disbursement Form"
    "财务团队处理贷款放款的表单" = "Form for finance team to process loan disbursements"
    
    # Action descriptions
    "提交贷款申请开始审批流程" = "Submit loan application to start approval process"
    "撤回已提交的贷款申请" = "Withdraw submitted loan application"
    "打开信用检查表单记录信用局结果" = "Open credit check form to record credit bureau results"
    "查看信用检查结果（只读）" = "View credit check results (read-only)"
    "对贷款申请进行风险评估" = "Perform risk assessment on loan application"
    "批准贷款申请" = "Approve loan application"
    "拒绝贷款申请" = "Reject loan application"
    "向申请人请求补充信息" = "Request additional information from applicant"
    "验证所有上传的文档" = "Verify all uploaded documents"
    "根据贷款金额和期限计算月供" = "Calculate EMI based on loan amount and tenure"
    "处理贷款放款到申请人账户" = "Process loan disbursement to applicant account"
    "使用过滤条件查询贷款申请" = "Query loan applications with filters"
    "验证申请人的银行账户" = "Verify applicant's bank account"
    "将贷款标记为低风险" = "Mark loan as low risk"
    "将贷款标记为高风险" = "Mark loan as high risk"
    
    # Action config messages
    "确认提交此贷款申请？" = "Confirm submission of this loan application?"
    "贷款申请已成功提交" = "Loan application submitted successfully"
    "确认撤回此贷款申请？" = "Confirm withdrawal of this loan application?"
    "贷款申请已撤回" = "Loan application withdrawn"
    "信用检查结果已保存" = "Credit check results saved"
    "信用局检查" = "Credit Bureau Check"
    "信用报告" = "Credit Report"
    "风险评估与分析" = "Risk Assessment and Analysis"
    "风险评估已完成" = "Risk assessment completed"
    "确认批准此贷款申请？" = "Confirm approval of this loan application?"
    "贷款申请已批准" = "Loan application approved"
    "确认拒绝此贷款申请？" = "Confirm rejection of this loan application?"
    "贷款申请已拒绝" = "Loan application rejected"
    "请求补充信息" = "Request Additional Information"
    "请说明需要补充的信息" = "Please specify the information needed"
    "信息请求已发送给申请人" = "Information request sent to applicant"
    "文档验证成功" = "Document verification successful"
    "月供计算成功" = "EMI calculation successful"
    "确认处理此贷款的放款？" = "Confirm processing disbursement for this loan?"
    "贷款已成功放款" = "Loan disbursed successfully"
    "账户验证成功" = "Account verification successful"
    "已标记为低风险" = "Marked as low risk"
    "已标记为高风险" = "Marked as high risk"
    
    # Notice messages
    "创建主表：贷款申请" = "Created main table: Loan Application"
    "创建子表：申请人信息" = "Created sub table: Applicant Information"
    "创建子表：财务信息" = "Created sub table: Financial Information"
    "创建子表：抵押物信息" = "Created sub table: Collateral Details"
    "创建关联表：信用检查结果" = "Created relation table: Credit Check Results"
    "创建关联表：审批历史" = "Created relation table: Approval History"
    "创建关联表：文档附件" = "Created relation table: Documents"
    "创建表单：贷款申请表单" = "Created form: Loan Application Form"
    "创建表单：信用检查表单" = "Created form: Credit Check Form"
    "创建表单：风险评估表单" = "Created form: Risk Assessment Form"
    "创建表单：审批表单" = "Created form: Loan Approval Form"
    "创建表单：放款表单" = "Created form: Loan Disbursement Form"
    "创建了 15 个动作定义" = "Created 15 action definitions"
    "数字贷款系统 V2 创建成功！" = "Digital Lending System V2 created successfully!"
    "功能单元 ID:" = "Function Unit ID:"
    "表定义：" = "Table Definitions:"
    "贷款申请（主表）:" = "Loan Application (Main):"
    "申请人信息（子表）:" = "Applicant Information (Sub):"
    "财务信息（子表）:" = "Financial Information (Sub):"
    "抵押物信息（子表）:" = "Collateral Details (Sub):"
    "信用检查结果（关联表）:" = "Credit Check Results (Relation):"
    "审批历史（关联表）:" = "Approval History (Relation):"
    "文档附件（关联表）:" = "Documents (Relation):"
    "表单定义：" = "Form Definitions:"
    "贷款申请表单:" = "Loan Application Form:"
    "信用检查表单（弹窗）:" = "Credit Check Form (Popup):"
    "风险评估表单（弹窗）:" = "Risk Assessment Form (Popup):"
    "审批表单:" = "Loan Approval Form:"
    "放款表单:" = "Loan Disbursement Form:"
    "动作定义：15 个（包括弹窗表单动作和 API 调用）" = "Action Definitions: 15 (including popup form actions and API calls)"
    "下一步：" = "Next Steps:"
    "运行: 02-insert-bpmn-process.ps1" = "Run: 02-insert-bpmn-process.ps1"
    "运行: 03-bind-actions.sql" = "Run: 03-bind-actions.sql"
    "在开发者工作台部署功能单元" = "Deploy function unit in Developer Workstation"
    "在用户门户测试完整流程" = "Test complete workflow in User Portal"
    "提交申请" = "Submit Application"
}

# Apply translations
foreach ($key in $translations.Keys) {
    $content = $content -replace [regex]::Escape($key), $translations[$key]
}

# Save the translated content
$content | Set-Content $inputFile -Encoding UTF8 -NoNewline

Write-Host "Translation completed successfully!" -ForegroundColor Green
