import { parsePkGeneration } from './pkGenerationConfig'
import type { PkGenerationConfig } from './tableFkRuntime'

export type RuntimeFieldDefinition = {
  fieldName: string
  isPrimaryKey?: boolean
  primaryKey?: boolean
  isForeignKey?: boolean
  refTableId?: number
  refPrimaryKeyFields?: string[]
  pkGeneration?: PkGenerationConfig
  pkGenerationJson?: PkGenerationConfig | Record<string, unknown>
  fkDisplayMode?: 'readonly' | 'hidden' | string
}

function resolveIsPrimaryKey(field: RuntimeFieldDefinition): boolean {
  if (field.isPrimaryKey === true) return true
  return field.primaryKey === true
}

/** Normalize table field rows before PK allocation / readonly presentation (aligns with DW preview). */
export function normalizeFieldDefinitionForRuntime(field: RuntimeFieldDefinition): RuntimeFieldDefinition {
  const isPrimaryKey = resolveIsPrimaryKey(field)
  const pkGeneration = field.pkGeneration ?? field.pkGenerationJson
  return {
    ...field,
    isPrimaryKey,
    pkGeneration: isPrimaryKey ? (pkGeneration ?? { strategy: 'uuid' }) : pkGeneration,
  }
}

export function isAutoGeneratedPrimaryKey(field: RuntimeFieldDefinition): boolean {
  if (!resolveIsPrimaryKey(field)) return false
  const raw = field.pkGeneration ?? field.pkGenerationJson
  const pk = parsePkGeneration(raw as PkGenerationConfig | Record<string, unknown> | null | undefined)
  return pk.strategy !== 'manual'
}
