import { describe, expect, it } from 'vitest'
import type { FieldDefinition } from '@/api/functionUnit'
import {
  applyTableFieldMetaToFormRule,
  isAutoGeneratedPrimaryKey,
  normalizeFieldDefinitionForRuntime,
  shouldIncludeFieldOnFormCanvas,
  syncFormRulesWithTableFields,
  taskFieldPermissionForField,
} from '@/utils/formFieldMeta'

function field(partial: Partial<FieldDefinition> & Pick<FieldDefinition, 'fieldName'>): FieldDefinition {
  return {
    dataType: 'VARCHAR',
    nullable: true,
    isPrimaryKey: false,
    ...partial,
  }
}

describe('formFieldMeta', () => {
  it('omits hidden FK from canvas import', () => {
    const fk = field({
      fieldName: 'main_id',
      isForeignKey: true,
      fkDisplayMode: 'hidden',
      refTableId: 1,
      refPrimaryKeyFields: ['id'],
    })
    expect(shouldIncludeFieldOnFormCanvas(fk)).toBe(false)
  })

  it('omits platform audit fields from canvas import', () => {
    for (const name of ['created_at', 'created_by', 'updated_at', 'updated_by']) {
      expect(shouldIncludeFieldOnFormCanvas(field({ fieldName: name, dataType: 'TIMESTAMP' }))).toBe(false)
    }
  })

  it('removes audit field rules when syncing canvas with table metadata', () => {
    const fields = [field({ fieldName: 'name' })]
    const synced = syncFormRulesWithTableFields(
      [
        { field: 'name', type: 'input', props: {} },
        { field: 'created_at', type: 'input', props: {} },
      ],
      fields,
    ) as Array<Record<string, unknown>>
    expect(synced).toHaveLength(1)
    expect(synced[0].field).toBe('name')
  })

  it('marks readonly FK and auto PK on imported rules', () => {
    const fk = field({
      fieldName: 'main_id',
      isForeignKey: true,
      fkDisplayMode: 'readonly',
    })
    const pk = field({
      fieldName: 'id',
      isPrimaryKey: true,
      pkGeneration: { strategy: 'uuid' },
    })

    const fkRule = applyTableFieldMetaToFormRule(fk, { field: 'main_id', type: 'input', props: {} })
    const pkRule = applyTableFieldMetaToFormRule(pk, { field: 'id', type: 'input', props: {} })

    expect(fkRule.readonly).toBe(true)
    expect(pkRule.readonly).toBe(true)
    expect(taskFieldPermissionForField(fk)).toBe('READONLY')
    expect(taskFieldPermissionForField(pk)).toBe('READONLY')
  })

  it('marks computed fields readonly and locks task permission', () => {
    const computed = field({
      fieldName: 'total',
      isComputed: true,
    })
    const rule = applyTableFieldMetaToFormRule(computed, { field: 'total', type: 'input', props: {} })
    expect(rule.readonly).toBe(true)
    expect(taskFieldPermissionForField(computed)).toBe('READONLY')
  })

  it('respects designer readonly=false override on auto PK after save reload sync', () => {
    const pk = field({
      fieldName: 'case_number',
      isPrimaryKey: true,
      pkGeneration: { strategy: 'uuid' },
    })
    const rule = applyTableFieldMetaToFormRule(pk, {
      field: 'case_number',
      type: 'input',
      props: { readonly: false },
      readonly: false,
    }) as Record<string, unknown>
    expect(rule.readonly).toBe(false)
    expect((rule.props as Record<string, unknown>).readonly).toBe(false)
  })

  it('syncs existing canvas rules from table metadata', () => {
    const fields = [
      field({
        fieldName: 'main_id',
        isForeignKey: true,
        fkDisplayMode: 'readonly',
      }),
      field({
        fieldName: 'secret_fk',
        isForeignKey: true,
        fkDisplayMode: 'hidden',
      }),
    ]
    const synced = syncFormRulesWithTableFields(
      [
        { field: 'name', type: 'input', props: {} },
        { field: 'main_id', type: 'input', props: {} },
        { field: 'secret_fk', type: 'input', props: {} },
      ],
      fields,
    ) as Array<Record<string, unknown>>

    expect(synced).toHaveLength(2)
    expect(synced.find(r => r.field === 'secret_fk')).toBeUndefined()
    expect((synced.find(r => r.field === 'main_id')?.props as Record<string, unknown>).readonly).toBe(true)
  })

  it('marks auto PK readonly inside elCard children (Form Preview layout)', () => {
    const fields = [
      field({
        fieldName: 'id',
        isPrimaryKey: true,
        pkGeneration: { strategy: 'uuid' },
      }),
    ]
    const synced = syncFormRulesWithTableFields(
      [
        {
          type: 'elCard',
          props: { header: 'Title' },
          children: [{ field: 'id', type: 'input', props: { maxlength: 222 } }],
        },
      ],
      fields,
    ) as Array<Record<string, unknown>>

    const cardChild = ((synced[0].children as Array<Record<string, unknown>>) || [])[0]
    expect(cardChild.readonly).toBe(true)
    expect((cardChild.props as Record<string, unknown>).readonly).toBe(true)
  })

  it('treats legacy primaryKey JSON alias as PK metadata', () => {
    const pk = normalizeFieldDefinitionForRuntime({
      fieldName: 'id',
      dataType: 'VARCHAR',
      nullable: true,
      primaryKey: true,
      pkGenerationJson: { strategy: 'uuid' },
    } as FieldDefinition & { primaryKey: boolean })

    expect(isAutoGeneratedPrimaryKey(pk)).toBe(true)
  })
})
