apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workflow-platform-ingress-gateway.yaml
  - redis.yaml
  - kafka.yaml
  - activepieces.yaml
  - workflow-station-superset.yaml
  - workflow-engine.yaml
  - admin-center.yaml
  - user-portal.yaml
  - kong.yaml
  - admin-center-frontend.yaml
  - user-portal-frontend.yaml
  - platform-login-frontend.yaml