/**
 * Platform-managed audit fields — EXACT four names only (case-insensitive, trimmed):
 * created_at / created_by / updated_at / updated_by.
 *
 * CANONICAL frontend copy of the decision "is this a system audit field?".
 * Must stay in sync with backend platform-common `SystemAuditFields` (the write-side
 * authority). No fuzzy matching (create_time / createUser variants never count): the
 * names are generated by Table Design and are always exactly these four; fuzzy matching
 * would misclassify user-defined business fields of the same-ish name (editable in the
 * designer yet locked/overwritten at runtime). Verified 2026-07: no fuzzy-variant field
 * exists in any live table.
 */

export const SYSTEM_AUDIT_FIELDS = ['created_at', 'created_by', 'updated_at', 'updated_by'] as const

export const SYSTEM_AUDIT_FIELD_SET: ReadonlySet<string> = new Set(SYSTEM_AUDIT_FIELDS)

/** Normalise for comparison: trim + lowercase (underscores kept — exact names only). */
export function normalizeAuditFieldName(name: string): string {
  return name.trim().toLowerCase()
}

/** True when the field name is one of the four platform-managed audit fields. */
export function isSystemAuditField(fieldName: string): boolean {
  return SYSTEM_AUDIT_FIELD_SET.has(normalizeAuditFieldName(fieldName))
}

/** created_at / updated_at — timestamps even when a legacy table declared them as text. */
export function isAuditTimestampField(fieldName: string): boolean {
  const name = normalizeAuditFieldName(fieldName)
  return name === 'created_at' || name === 'updated_at'
}

/** created_by / updated_by — a person, even when a legacy table declared them as text. */
export function isAuditUserField(fieldName: string): boolean {
  const name = normalizeAuditFieldName(fieldName)
  return name === 'created_by' || name === 'updated_by'
}
