FROM nginx:alpine
RUN apk add --no-cache gettext
COPY dist /usr/share/nginx/html/login
COPY nginx.conf /etc/nginx/conf.d/default.conf.template
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN sed -i 's/\r$//' /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh
ENV KONG_PROXY_URL=http://kong:8000
EXPOSE 80
ENTRYPOINT ["/docker-entrypoint.sh"]
