import type { FieldDefinition } from '@/api/functionUnit'
import { getRuleChildren } from '@/utils/formDesigner'
import { parsePkGeneration } from '@/utils/pkGenerationConfig'
import { isFkHidden, isFkReadonly, type FieldFkMeta } from '@/utils/tableFkRuntime'

export type TaskFieldPermission = 'EDITABLE' | 'READONLY'

function toFkMeta(field: FieldDefinition): FieldFkMeta {
  return {
    fieldName: field.fieldName,
    isForeignKey: field.isForeignKey,
    refTableId: field.refTableId,
    refPrimaryKeyFields: field.refPrimaryKeyFields,
    fkDisplayMode: field.fkDisplayMode,
  }
}

/** Hidden structural FK: omit from form canvas; runtime still fills via fieldDefinitions. */
export function shouldIncludeFieldOnFormCanvas(field: FieldDefinition): boolean {
  if (!field?.fieldName?.trim()) return false
  if (field.isForeignKey && isFkHidden(toFkMeta(field))) return false
  return true
}

function resolveIsPrimaryKey(field: FieldDefinition): boolean {
  if (field.isPrimaryKey === true) return true
  const legacy = field as FieldDefinition & { primaryKey?: boolean }
  return legacy.primaryKey === true
}

/** Normalize API/store field rows before applying canvas / preview metadata. */
export function normalizeFieldDefinitionForRuntime(field: FieldDefinition): FieldDefinition {
  const isPrimaryKey = resolveIsPrimaryKey(field)
  const pkGeneration = field.pkGeneration ?? field.pkGenerationJson
  return {
    ...field,
    isPrimaryKey,
    pkGeneration: isPrimaryKey ? (pkGeneration ?? { strategy: 'uuid' }) : pkGeneration,
  }
}

export function isAutoGeneratedPrimaryKey(field: FieldDefinition): boolean {
  if (!resolveIsPrimaryKey(field)) return false
  const raw = field.pkGeneration ?? field.pkGenerationJson
  const pk = parsePkGeneration(raw)
  return pk.strategy !== 'manual'
}

export function applyTableFieldMetaToFormRule(
  field: FieldDefinition,
  rule: Record<string, unknown>,
): Record<string, unknown> {
  const props = { ...((rule.props as Record<string, unknown> | undefined) || {}) }
  let readonly = props.readonly === true || rule.readonly === true

  if (field.isForeignKey && isFkReadonly(toFkMeta(field))) {
    readonly = true
  }
  if (isAutoGeneratedPrimaryKey(field)) {
    readonly = true
  }

  if (!readonly) return rule

  props.readonly = true
  return { ...rule, props, readonly: true }
}

const RULE_CHILD_LOCATIONS: Array<{ parent: 'root' | 'props'; key: string }> = [
  { parent: 'root', key: 'children' },
  { parent: 'props', key: 'children' },
  { parent: 'props', key: 'list' },
  { parent: 'props', key: 'items' },
  { parent: 'props', key: 'fields' },
]

function findRuleChildLocation(rule: Record<string, unknown>): { parent: 'root' | 'props'; key: string } | null {
  for (const loc of RULE_CHILD_LOCATIONS) {
    const arr = loc.parent === 'root'
      ? rule[loc.key]
      : (rule.props as Record<string, unknown> | undefined)?.[loc.key]
    if (Array.isArray(arr)) return loc
  }
  return null
}

function withSyncedRuleChildren(rule: Record<string, unknown>, syncedChildren: unknown[]): Record<string, unknown> {
  const loc = findRuleChildLocation(rule)
  if (!loc) return rule
  if (loc.parent === 'root') {
    return { ...rule, [loc.key]: syncedChildren }
  }
  const props = { ...((rule.props as Record<string, unknown> | undefined) || {}) }
  props[loc.key] = syncedChildren
  return { ...rule, props }
}

function syncRuleNode(rule: unknown, fieldByName: Map<string, FieldDefinition>): unknown | null {
  if (!rule || typeof rule !== 'object') return rule
  const r = rule as Record<string, unknown>
  const fieldName = typeof r.field === 'string' ? r.field : ''
  const field = fieldName ? fieldByName.get(fieldName) : undefined

  if (field && !shouldIncludeFieldOnFormCanvas(field)) {
    return null
  }

  const children = getRuleChildren(r)
  let next: Record<string, unknown> = field
    ? applyTableFieldMetaToFormRule(field, r)
    : { ...r }

  if (children.length) {
    const syncedChildren = children
      .map(child => syncRuleNode(child, fieldByName))
      .filter((child): child is unknown => child != null)
    next = withSyncedRuleChildren(next, syncedChildren)
  }

  return next
}

export function syncFormRulesWithTableFields(
  rules: unknown[],
  fields: FieldDefinition[],
): unknown[] {
  if (!Array.isArray(rules) || !fields?.length) return rules
  const fieldByName = new Map(
    fields
      .filter(f => f.fieldName)
      .map(f => [f.fieldName, normalizeFieldDefinitionForRuntime(f)]),
  )

  return rules
    .map(rule => syncRuleNode(rule, fieldByName))
    .filter((rule): rule is unknown => rule != null)
}

export function taskFieldPermissionForField(field: FieldDefinition): TaskFieldPermission | null {
  if (field.isForeignKey && isFkReadonly(toFkMeta(field))) {
    return 'READONLY'
  }
  if (isAutoGeneratedPrimaryKey(field)) {
    return 'READONLY'
  }
  return null
}

export function applyTaskFieldPermissionsFromTableFields(
  fieldPermissions: Record<string, string> | undefined,
  fields: FieldDefinition[],
): Record<string, string> {
  const next = { ...(fieldPermissions || {}) }
  for (const field of fields) {
    const perm = taskFieldPermissionForField(field)
    if (perm) {
      next[field.fieldName] = perm
    }
  }
  return next
}
