import type { FieldDefinition, RequestIdConfig } from '@/api/functionUnit'
import { getRuleChildren } from '@/utils/formDesigner'
import { parsePkGeneration } from '@/utils/pkGenerationConfig'
import { isFkHidden, isFkReadonly, type FieldFkMeta } from '@/utils/tableFkRuntime'
import { isTableAuditField } from '@/utils/tableAuditFields'

export type TaskFieldPermission = 'EDITABLE' | 'READONLY'

/**
 * 保留 field 名:Request ID 是一个跨字段拼接的派生只读字段,作为一条 synthetic form-create
 * rule 默认导入到 main form。不能与真实 fieldName 冲突(双下划线前缀约定保留)。
 */
export const REQUEST_ID_FIELD = '__request_id'

/** 该 rule 是否是 Request ID synthetic 字段(用于去重 / 运行时取值识别)。 */
export function isRequestIdRule(rule: unknown): boolean {
  if (!rule || typeof rule !== 'object') return false
  const r = rule as Record<string, unknown>
  return r._requestId === true || r.field === REQUEST_ID_FIELD
}

/**
 * 构建 Request ID 的 synthetic 只读 form-create rule。
 * 复用现有 readonly 机制(props.readonly → 渲染时转 disabled);值在运行时由后端填充。
 */
export function buildRequestIdFormRule(label: string): Record<string, unknown> {
  return {
    field: REQUEST_ID_FIELD,
    title: label,
    type: 'input',
    _requestId: true,
    readonly: true,
    props: { readonly: true },
    validate: [],
  }
}

/** 主表配了 Request ID 才需要 synthetic 字段。 */
export function hasRequestIdConfig(config?: RequestIdConfig | null): boolean {
  return !!config && Array.isArray(config.fieldNames) && config.fieldNames.length > 0
}

/** 导入字段对话框里展示该 synthetic 字段的 dataType 标记(虚拟,非真实列类型)。 */
export const REQUEST_ID_DATA_TYPE = 'REQUEST_ID'

/**
 * 构建一个"可勾选的虚拟字段",注入到导入对话框的可选字段列表里。
 * 勾选并导入后,由 {@link fieldToFormRule}(经 {@link isRequestIdSyntheticField})转成只读 rule。
 */
export function buildRequestIdSyntheticField(label: string): FieldDefinition {
  return {
    fieldName: REQUEST_ID_FIELD,
    dataType: REQUEST_ID_DATA_TYPE,
    nullable: true,
    isPrimaryKey: false,
    displayName: label,
    // 标记位:identifies this as the virtual Request ID field across the import flow
    _requestId: true,
  } as FieldDefinition & { _requestId: boolean }
}

/** 该 FieldDefinition 是否是 Request ID 虚拟字段(import 列表 / 已选列表识别)。 */
export function isRequestIdSyntheticField(field?: { fieldName?: string; dataType?: string } | null): boolean {
  if (!field) return false
  const f = field as { fieldName?: string; dataType?: string; _requestId?: boolean }
  return f._requestId === true || f.dataType === REQUEST_ID_DATA_TYPE || f.fieldName === REQUEST_ID_FIELD
}

function toFkMeta(field: FieldDefinition): FieldFkMeta {
  return {
    fieldName: field.fieldName,
    isForeignKey: field.isForeignKey,
    refTableId: field.refTableId,
    refPrimaryKeyFields: field.refPrimaryKeyFields,
    fkDisplayMode: field.fkDisplayMode,
  }
}

/**
 * Hidden structural FK: omit from the form canvas (runtime still fills them).
 * Platform audit fields (created_at/by, updated_at/by) ARE allowed — designers
 * may import them as readonly display controls. Values stay server-filled.
 */
export function shouldIncludeFieldOnFormCanvas(field: FieldDefinition): boolean {
  if (!field?.fieldName?.trim()) return false
  if (field.isForeignKey && isFkHidden(toFkMeta(field))) return false
  return true
}

function resolveIsPrimaryKey(field: FieldDefinition): boolean {
  if (field.isPrimaryKey === true) return true
  const legacy = field as FieldDefinition & { primaryKey?: boolean }
  return legacy.primaryKey === true
}

/** Normalize API/store field rows before applying canvas / preview metadata. */
export function normalizeFieldDefinitionForRuntime(field: FieldDefinition): FieldDefinition {
  const isPrimaryKey = resolveIsPrimaryKey(field)
  const pkGeneration = field.pkGeneration ?? field.pkGenerationJson
  return {
    ...field,
    isPrimaryKey,
    pkGeneration: isPrimaryKey ? (pkGeneration ?? { strategy: 'uuid' }) : pkGeneration,
  }
}

export function isAutoGeneratedPrimaryKey(field: FieldDefinition): boolean {
  if (!resolveIsPrimaryKey(field)) return false
  const raw = field.pkGeneration ?? field.pkGenerationJson
  const pk = parsePkGeneration(raw)
  return pk.strategy !== 'manual'
}

export function isComputedTableField(field: FieldDefinition): boolean {
  return field.isComputed === true
}

export function applyTableFieldMetaToFormRule(
  field: FieldDefinition,
  rule: Record<string, unknown>,
): Record<string, unknown> {
  const props = { ...((rule.props as Record<string, unknown> | undefined) || {}) }

  // Audit columns are platform-filled at insert/update — always locked, even if
  // the designer Readonly toggle was turned off (Portal also forces this).
  if (isTableAuditField(field.fieldName)) {
    props.readonly = true
    return { ...rule, props, readonly: true }
  }

  // Designer explicitly turned Readonly off — do not re-apply PK/FK readonly after Save reload.
  if (props.readonly === false || rule.readonly === false) {
    delete props.disabled
    const next: Record<string, unknown> = { ...rule, props, readonly: false }
    delete next.disabled
    return next
  }

  let readonly = props.readonly === true || rule.readonly === true

  if (field.isForeignKey && isFkReadonly(toFkMeta(field))) {
    readonly = true
  }
  if (isAutoGeneratedPrimaryKey(field)) {
    readonly = true
  }
  if (isComputedTableField(field)) {
    readonly = true
  }

  if (!readonly) return rule

  props.readonly = true
  return { ...rule, props, readonly: true }
}

const RULE_CHILD_LOCATIONS: Array<{ parent: 'root' | 'props'; key: string }> = [
  { parent: 'root', key: 'children' },
  { parent: 'props', key: 'children' },
  { parent: 'props', key: 'list' },
  { parent: 'props', key: 'items' },
  { parent: 'props', key: 'fields' },
]

function findRuleChildLocation(rule: Record<string, unknown>): { parent: 'root' | 'props'; key: string } | null {
  for (const loc of RULE_CHILD_LOCATIONS) {
    const arr = loc.parent === 'root'
      ? rule[loc.key]
      : (rule.props as Record<string, unknown> | undefined)?.[loc.key]
    if (Array.isArray(arr)) return loc
  }
  return null
}

function withSyncedRuleChildren(rule: Record<string, unknown>, syncedChildren: unknown[]): Record<string, unknown> {
  const loc = findRuleChildLocation(rule)
  if (!loc) return rule
  if (loc.parent === 'root') {
    return { ...rule, [loc.key]: syncedChildren }
  }
  const props = { ...((rule.props as Record<string, unknown> | undefined) || {}) }
  props[loc.key] = syncedChildren
  return { ...rule, props }
}

function syncRuleNode(rule: unknown, fieldByName: Map<string, FieldDefinition>): unknown | null {
  if (!rule || typeof rule !== 'object') return rule
  const r = rule as Record<string, unknown>
  const fieldName = typeof r.field === 'string' ? r.field : ''
  const field = fieldName ? fieldByName.get(fieldName) : undefined

  if (field && !shouldIncludeFieldOnFormCanvas(field)) {
    return null
  }

  const children = getRuleChildren(r)
  let next: Record<string, unknown> = field
    ? applyTableFieldMetaToFormRule(field, r)
    : { ...r }

  if (children.length) {
    const syncedChildren = children
      .map(child => syncRuleNode(child, fieldByName))
      .filter((child): child is unknown => child != null)
    next = withSyncedRuleChildren(next, syncedChildren)
  }

  return next
}

export function syncFormRulesWithTableFields(
  rules: unknown[],
  fields: FieldDefinition[],
): unknown[] {
  if (!Array.isArray(rules) || !fields?.length) return rules
  const fieldByName = new Map(
    fields
      .filter(f => f.fieldName)
      .map(f => [f.fieldName, normalizeFieldDefinitionForRuntime(f)]),
  )

  return rules
    .map(rule => syncRuleNode(rule, fieldByName))
    .filter((rule): rule is unknown => rule != null)
}

export function taskFieldPermissionForField(field: FieldDefinition): TaskFieldPermission | null {
  if (isTableAuditField(field.fieldName)) {
    return 'READONLY'
  }
  if (field.isForeignKey && isFkReadonly(toFkMeta(field))) {
    return 'READONLY'
  }
  if (isAutoGeneratedPrimaryKey(field)) {
    return 'READONLY'
  }
  if (isComputedTableField(field)) {
    return 'READONLY'
  }
  return null
}

/**
 * bindingId 非空时用复合 key `${bindingId}:${fieldName}` 写入子表字段权限,
 * 避免与主表或其它子表同名字段互相覆盖(见 subtable field permission collision)。
 */
export function applyTaskFieldPermissionsFromTableFields(
  fieldPermissions: Record<string, string> | undefined,
  fields: FieldDefinition[],
  bindingId?: number,
): Record<string, string> {
  const next = { ...(fieldPermissions || {}) }
  for (const field of fields) {
    const perm = taskFieldPermissionForField(field)
    if (perm) {
      next[bindingId != null ? `${bindingId}:${field.fieldName}` : field.fieldName] = perm
    }
  }
  return next
}
