<template>
  <div class="page-container">
    <PageHeader :title="isEdit ? t('form.titleEditTableStructure') : t('form.titleCreateTableStructure')">
      <template #actions>
        <el-button @click="router.back()">
          {{ t('form.back') }}
        </el-button>
      </template>
    </PageHeader>

    <el-form
      ref="formRef"
      :model="form"
      :rules="rules"
      label-width="140px"
      label-position="left"
      style="max-width: 800px;"
    >
      <el-form-item
        :label="t('form.labelDisplayName')"
        prop="displayName"
        required
      >
        <el-input
          v-model="form.displayName"
          :placeholder="t('form.placeholderDisplayName')"
          @input="onTableDisplayNameInput"
        />
      </el-form-item>
      <el-form-item
        :label="t('form.labelTableName')"
        prop="tableName"
      >
        <el-input
          v-model="form.tableName"
          :placeholder="t('form.placeholderTableName')"
          disabled
        />
        <div
          v-if="!isEdit"
          class="form-item-hint"
        >
          {{ t('form.hintTableNameAutoGenerated') }}
        </div>
      </el-form-item>
      <el-form-item
        :label="t('form.labelDescription')"
        prop="description"
      >
        <el-input
          v-model="form.description"
          type="textarea"
          :rows="3"
          :placeholder="t('form.placeholderTableDescription')"
        />
      </el-form-item>
      <el-form-item
        :label="t('form.labelFunctionUnit')"
        prop="functionUnitIds"
      >
        <el-select
          v-model="form.functionUnitIds"
          multiple
          clearable
          filterable
          :placeholder="t('form.placeholderSelectFunctionUnit')"
          style="width: 100%;"
        >
          <el-option
            v-for="fu in allFunctionUnitOptions"
            :key="fu.id"
            :label="fu.name || fu.code"
            :value="fu.id"
          />
        </el-select>
        <div class="form-item-hint">
          {{ t('form.hintEmptyMeansCommon') }}
        </div>
      </el-form-item>
    </el-form>

    <div style="margin-top: 24px;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
        <span style="font-size: 16px; font-weight: 600;">{{ t('form.labelFieldDefinitions') }}</span>
        <el-button
          type="primary"
          size="small"
          @click="addField"
        >
          <el-icon><Plus /></el-icon>{{ t('form.addField') }}
        </el-button>
      </div>

      <el-table
        :data="form.fieldDefinitions"
        border
      >
        <el-table-column
          label="#"
          width="50"
          align="center"
        >
          <template #default="{ $index }">
            {{ $index + 1 }}
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelDisplayName')"
          min-width="140"
        >
          <template #default="{ row, $index }">
            <el-input
              v-model="row.displayName"
              :placeholder="t('form.placeholderDisplayName')"
              size="small"
              :disabled="isAuditField(row)"
              @input="onFieldDisplayNameInput(row, $index)"
            />
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelFieldName')"
          min-width="140"
        >
          <template #default="{ row }">
            <el-input
              v-model="row.fieldName"
              :placeholder="t('form.placeholderFieldName')"
              size="small"
              :disabled="isAuditField(row)"
              @input="onFieldNameManualInput(row)"
            />
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelType')"
          width="140"
        >
          <template #default="{ row }">
            <el-select
              v-model="row.dataType"
              :placeholder="t('form.placeholderDataType')"
              size="small"
              style="width: 100%;"
              :disabled="isAuditField(row)"
            >
              <el-option
                v-for="dt in dataTypes"
                :key="dt"
                :label="dt"
                :value="dt"
              />
            </el-select>
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelLength')"
          width="90"
        >
          <template #default="{ row }">
            <el-input-number
              v-model="row.length"
              :min="0"
              size="small"
              controls-position="right"
              style="width: 100%;"
              :disabled="isAuditField(row)"
            />
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelNullable')"
          width="80"
          align="center"
        >
          <template #default="{ row }">
            <el-switch
              v-model="row.nullable"
              size="small"
              :disabled="isAuditField(row)"
            />
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelPrimaryKey')"
          min-width="200"
        >
          <template #default="{ row }">
            <div class="pk-cell">
              <el-switch
                v-model="row.isPrimaryKey"
                size="small"
                :disabled="isAuditField(row)"
                @change="(val: boolean) => onPrimaryKeyChange(row, val)"
              />
              <PkGenerationEditor
                v-if="row.isPrimaryKey && !isAuditField(row)"
                v-model="row.pkGeneration"
                :enabled="true"
              />
            </div>
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelForeignKey')"
          width="110"
          align="center"
        >
          <template #default="{ row }">
            <FieldForeignKeyEditor
              :is-foreign-key="row.isForeignKey"
              :ref-table-id="row.refTableId"
              :ref-primary-key-fields="row.refPrimaryKeyFields"
              :ref-tables="fkRefTables"
              :disabled="isAuditField(row)"
              @update:is-foreign-key="row.isForeignKey = $event"
              @update:ref-table-id="row.refTableId = $event"
              @update:ref-primary-key-fields="row.refPrimaryKeyFields = $event"
            />
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelLookup')"
          width="90"
          align="center"
        >
          <template #default="{ row }">
            <FieldLookupEditor
              v-if="row.dataType === 'LOOKUP' && !isAuditField(row)"
              :model-value="row.lookupConfig"
              :ref-tables="fkRefTables"
              :all-fields="form.fieldDefinitions"
              :current-field-name="row.fieldName"
              @update:model-value="row.lookupConfig = $event"
            />
            <span
              v-else
              class="lookup-na"
            >—</span>
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelComputed')"
          width="110"
          align="center"
        >
          <template #default="{ row }">
            <ComputedFieldEditor
              v-if="canBeComputed(row)"
              :is-computed="row.isComputed"
              :computed-field="row.computedField"
              @update:is-computed="row.isComputed = $event"
              @update:computed-field="row.computedField = $event"
            />
            <span
              v-else
              class="lookup-na"
            >—</span>
          </template>
        </el-table-column>
        <el-table-column
          :label="t('form.labelDefaultValue')"
          width="130"
        >
          <template #default="{ row }">
            <el-input
              v-model="row.defaultValue"
              placeholder=""
              size="small"
              :disabled="isAuditField(row)"
            />
          </template>
        </el-table-column>
        <el-table-column
          label=""
          width="60"
          align="center"
        >
          <template #default="{ row, $index }">
            <el-button
              v-if="!isAuditField(row)"
              link
              type="danger"
              size="small"
              @click="removeField($index)"
            >
              <el-icon><Delete /></el-icon>
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </div>

    <div style="margin-top: 24px;">
      <el-button
        type="primary"
        :loading="submitting"
        @click="handleSubmit"
      >
        {{ isEdit ? t('form.saveChanges') : t('form.createTable') }}
      </el-button>
      <el-button @click="router.back()">
        {{ t('common.cancel') }}
      </el-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, toRef } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { Plus, Delete } from '@element-plus/icons-vue'
import type { FormInstance } from 'element-plus'
import PageHeader from '@/components/PageHeader.vue'
import PkGenerationEditor from '@/components/relation-table/PkGenerationEditor.vue'
import FieldForeignKeyEditor from '@/components/relation-table/FieldForeignKeyEditor.vue'
import FieldLookupEditor from '@/components/relation-table/FieldLookupEditor.vue'
import ComputedFieldEditor from '@/components/relation-table/ComputedFieldEditor.vue'
import { useTableStructureForm } from '@/composables/modules/useTableStructureForm'

const { t } = useI18n()
const router = useRouter()
const route = useRoute()

const isEdit = computed(() => !!route.params.id)
const tableId = computed(() => Number(route.params.id))
const formRef = ref<FormInstance>()

const { form, rules, submitting, dataTypes, fkRefTables, allFunctionUnitOptions, isAuditField, canBeComputed, addField, removeField, loadTableData, submit,
  onFieldDisplayNameInput, onFieldNameManualInput, onTableDisplayNameInput, onPrimaryKeyChange }
  = useTableStructureForm({ tableId, isEdit: toRef(isEdit) })

const handleSubmit = async () => {
  if (!await formRef.value?.validate().catch(() => false)) return
  if (await submit()) router.push('/relation-tables/structure')
}

onMounted(loadTableData)
</script>

<style scoped>
.page-container {
  padding: 20px;
}
.form-item-hint {
  margin-top: 4px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
  line-height: 1.4;
}
.pk-cell {
  display: flex;
  flex-direction: column;
  align-items: stretch;
  gap: 6px;
  padding: 2px 0;
  min-width: 180px;
}
.lookup-na {
  color: var(--el-text-color-placeholder);
}
</style>
