packages:
  - "packages/shared"
  - "packages/cli"
  - "packages/server/engine"
  - "packages/web"
  - "packages/server/api"
  - "packages/server/utils"
  - "packages/server/worker"
  - "packages/ee/embed-sdk"
  - "packages/tests-e2e"
  - "packages/pieces/framework"
  - "packages/pieces/common"
  - "packages/pieces/community/*"
